CREATE TABLE IF NOT EXISTS "User" (
    id UUID PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "TaskGroup" (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id UUID REFERENCES "User"(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "Task" (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    detail TEXT,
    is_completed BOOLEAN DEFAULT FALSE,
    task_group_id UUID REFERENCES "TaskGroup"(id) ON DELETE CASCADE
);
